# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class Oil(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    hardness = ... # type: builtin___float
    prices = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        hardness : typing___Optional[builtin___float] = None,
        prices : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Oil: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Oil: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"hardness",b"hardness",u"name",b"name",u"prices",b"prices"]) -> None: ...
global___Oil = Oil

class OilGroup(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    refinement_limit = ... # type: builtin___int

    @property
    def oils(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[global___Oil]: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        oils : typing___Optional[typing___Iterable[global___Oil]] = None,
        refinement_limit : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> OilGroup: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> OilGroup: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"oils",b"oils",u"refinement_limit",b"refinement_limit"]) -> None: ...
global___OilGroup = OilGroup

class Problem(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    final_product_price = ... # type: builtin___int
    storage_limit = ... # type: builtin___int
    storage_cost = ... # type: builtin___int
    hardness_lower_limit = ... # type: builtin___int
    hardness_upper_limit = ... # type: builtin___int
    n_months = ... # type: builtin___int

    @property
    def oil_groups(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[global___OilGroup]: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        final_product_price : typing___Optional[builtin___int] = None,
        oil_groups : typing___Optional[typing___Iterable[global___OilGroup]] = None,
        storage_limit : typing___Optional[builtin___int] = None,
        storage_cost : typing___Optional[builtin___int] = None,
        hardness_lower_limit : typing___Optional[builtin___int] = None,
        hardness_upper_limit : typing___Optional[builtin___int] = None,
        n_months : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Problem: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Problem: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"final_product_price",b"final_product_price",u"hardness_lower_limit",b"hardness_lower_limit",u"hardness_upper_limit",b"hardness_upper_limit",u"n_months",b"n_months",u"name",b"name",u"oil_groups",b"oil_groups",u"storage_cost",b"storage_cost",u"storage_limit",b"storage_limit"]) -> None: ...
global___Problem = Problem
